language: python
os: linux

python:
  - '3.6'

jobs:
  include:
    - stage: lint
      install:
        - pip install -U pip flake8
      script:
        - flake8 apollo --ignore=E501,W503 --exclude=arrow/commands/,scripts/
    - stage: test
      install:
        - pip install -U pip setuptools nose arrow
      script:
        - echo "Running Test"
        - python setup.py install
        - export ARROW_GLOBAL_CONFIG_PATH=`pwd`/test-data/arrow.yml
        - ./bootstra_apollo.sh
        - nosetests
        - echo "Finishing Test"
    - stage: load
      install:
        - pip install -U pip setuptools nose arrow
      script:
        - echo "Loading data"
        - python setup.py install
        - export ARROW_GLOBAL_CONFIG_PATH=`pwd`/test-data/arrow.yml
        - ./load_data.sh
        - nosetests
        - echo "Finished Loading Data"


#install:
#  - pip install -U pip setuptools nose

#script:
#  - echo "Running Test"
#  - python setup.py install
#  - export ARROW_GLOBAL_CONFIG_PATH=`pwd`/test-data/arrow.yml
#  - ./load_data.sh
#  - nosetests
#  - echo "Finishing Test"

stages:
  - lint
  - test
  - load
